---
title: "Democracia Local: Clientelismo, capital social e innovación política en la Argentina"
author: 
  - Samuel Amaral
  - Susan C. Stokes
year: 2005
publisher: Editorial de la Universidad Nacional de Tres de Febrero
filters: ["add-publisher.lua"]
format:
  html:
    title-block-style: default
---

<a role="button" href="https://www.amazon.com/Democracia-Local-Clientelismo-Innovacion-Argentina/dp/9871172079" type="button" class="btn btn-outline-secondary btn-xs"> <i class="bi bi-cart3 ai-lg"></i> Purchase here </a>

La calidad de la democracy - su capacidad de provocar la participación de la ciudadanía, de estimular debates y delieración sobra las opcioes que enfrenta un país o una comunidad, de proteger los derechos de los individuos y grupos marginales frente a los grupos de poder, de promover la justicia social - casi siempre se analiza desde la perspectiva de los gobiernos y de los procesos políticos nacionales.

La calidad de la democracia, sin embargo, también se advierte muchas veces de manera más cercana en el ámbito local: los ciudadanos estamos en contacto con los partidos políticos frecuentemente a través de dirigentes o candidatos locales, recibimos subsidios y programas sociales a través de los municipios, y estamos inmersos en redes sociales que giran alrededor de nuestro lugar de residencia. Es en ese ámbito, por lo tanto, donde se dan las relaciones más estrechas entre representantes y representados.

Aunque la calidad de la democracia siempre estará ligada a las instituciones, actores y procesos nacionales, también las instituciones, actores y procesos locales influyen profundamente en determinar esa calidad. La democracia, como la vivimos día a día, es también un fenómeno local.

Este libro estudia la formación de capital social, la práctica del clientelismo, la introducción de la innovación, y otros aspectos de la política tal como se la practica en municipios y localidades de la Argentina. Apunta, más que a denunciar situaciones o proponer soluciones, a llamar la atención sobre una dimensión clave de toda democracia: la democracia local.

[← Back to all books](/books/index.html)
